title: Site
options:
  # preview: https://website.net/

tabs:
  community:
    label: Communities
    icon: folder
    columns:
      - width: 1/2
        sections:
          publishedCommunity:
            type: pages
            headline: Published
            templates: community
            status: listed
            sortBy: title
      - width: 1/2
        sections:
          draftsCommunity:
            headline: Drafts
            type: pages
            status: draft
            templates: community
  metadata:
    label: Metrics
    icon: file
    columns:
      - width: 1/1
        sections:
          riskValues:
            type: fields
            fields:
              riskValues:
                label: Risk Values
                type: structure
                entry: "{{ riskValue }} - {{ riskColor }}"
                fields:
                  riskValue:
                    label: Risk Value
                    type: text
                  riskDescription:
                    label: Risk Description
                    type: textarea
                  riskColor:
                    label: Color
                    type: color
                    default: "#F05056"
                    presets:
                      - "#F05056"
                      - "#C42CAD"
                      - "#7401FA"
                      - "#0101FA"
                      - "#42B1E3"
                      - "#31E097"
                      - "#D2F417"
          # standardOfLiving:
          #   type: fields
          #   fields:
          #     standardOfLiving:
          #       label: Standard Of Living
          #       type: structure
          #       entry: "{{ riskValue }} - {{ riskColor }}"
          #       fields:
          #         standardOfLivingCategory:
          #           label: Category
          #           type: text
          #         riskDescription:
          #           label: Description
          #           type: textarea
          #         standardOfLivingTags:
          #           label: Tags
          #           type: tags
          #           width: 1/2
              tags:
                label: Tags
                type: tags
                width: 1/2
              alertRange:
                label: Display alerts for the last N months
                value: 7
                type: number
                width: 1/2
  highlight:
    label: Colophon
    icon: info
    columns:
      - width: 1/2
        sections:
          colophon:
            type: pages
            headline: Additional Pages
            template: page
            sortBy: sort
      - width: 1/1
        sections:
          seoA:
            type: fields
            fields:
              descriptionSEO:
                type: textarea
                label: Description for SEO
                buttons: false
                width: 1/2
              imageSEO:
                type: files
                multiple: false
                label: Image for SEO
                query: site.index.images
                width: 1/2
